version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: devsagency/pam
    versions:
    - 4.6.1
  - dependency-name: tracy/tracy
    versions:
    - 2.8.2
- package-ecosystem: npm
  directory: "/public"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: animadio
    versions:
    - 4.0.4
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.1.0
    - 4.1.3
    - 4.1.4
    - 4.1.7
    - 4.2.5
